"""Initial migration.

Revision ID: 0838b0f6c01d
Revises: 
Create Date: 2020-06-30 22:37:58.039560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0838b0f6c01d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deposit") as batch_op:
        batch_op.create_foreign_key('fk_wallet_deposit', 'wallet', ['wallet_id'], ['id'])
    with op.batch_alter_table("withdraw") as batch_op:
        batch_op.add_column(sa.Column('wallet_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_wallet_withdraw', 'wallet', ['wallet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'withdraw', type_='foreignkey')
    op.drop_column('withdraw', 'wallet_id')
    op.drop_constraint(None, 'deposit', type_='foreignkey')
    # ### end Alembic commands ###
