"""Second migration.

Revision ID: 59315baddb63
Revises: 0838b0f6c01d
Create Date: 2020-06-30 23:17:11.203268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59315baddb63'
down_revision = '0838b0f6c01d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deposit") as batch_op:
        batch_op.alter_column('plan_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
        batch_op.drop_column('successful_time')
        batch_op.drop_column('wallet_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit', sa.Column('wallet_id', sa.INTEGER(), nullable=True))
    op.add_column('deposit', sa.Column('successful_time', sa.DATETIME(), nullable=True))
    op.create_foreign_key('fk_wallet_deposit', 'deposit', 'wallet', ['wallet_id'], ['id'])
    op.alter_column('deposit', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
