"""fifth migration

Revision ID: c4cc0d359a63
Revises: 08630153b471
Create Date: 2020-07-02 00:00:35.396115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4cc0d359a63'
down_revision = '08630153b471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("withdraw") as batch_op:
        batch_op.add_column(sa.Column('is_successful', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('time_approved', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('withdraw', 'time_approved')
    op.drop_column('withdraw', 'is_successful')
    op.alter_column('deposit', 'wallet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('deposit', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('deposit', 'is_successful',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
