"""Third migration.

Revision ID: d3846f3e9213
Revises: 59315baddb63
Create Date: 2020-06-30 23:32:11.347534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3846f3e9213'
down_revision = '59315baddb63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deposit") as batch_op:
        batch_op.add_column(sa.Column('time_approved', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('wallet_id', sa.Integer(), nullable=True))

        batch_op.create_foreign_key('fk_wallet_deposit', 'wallet', ['wallet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deposit', type_='foreignkey')
    op.alter_column('deposit', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('deposit', 'wallet_id')
    op.drop_column('deposit', 'time_approved')
    # ### end Alembic commands ###
